machine:
  enabled: true
  docker_layer_caching: true

working_directory: ~/kubernetes-monitor

steps:
  - checkout

  - run:
      name: Get IP
      command: |
        IP=$(ifconfig -a | grep -A 1 eth0 | grep "inet addr:" | awk '{print $2}' | cut -d ':' -f2)
        echo "export IP=${IP} >> $BASH_ENV"

  - run:
      name: Download KinD
      command: |
        curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64
        chmod +x ./kind

  - run:
      name: Download kubectl
      command: |
        curl -L https://storage.googleapis.com/kubernetes-release/release/1.18.0/bin/linux/amd64/kubectl -o kubectl
        chmod +x ./kubectl

  - run:
      name: Create KinD cluster with private container registry
      command: |
        # create registry container unless it already exists
        reg_name=${IP}
        reg_port='5000'
        running="$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)"
        if [ "${running}" != 'true' ]; then
          docker run \
            -d --restart=always -p "${IP}:${reg_port}:5000" --name "${reg_name}" \
            registry:2
        fi

        sed -i "s|IP|${IP}|g" ./test/fixtures/cluster.yaml
        sed -i "s|PORT|${reg_port}|g" ./test/fixtures/cluster.yaml
        ./kind create cluster --config=./test/fixtures/cluster.yaml

        # connect the registry to the cluster network
        docker network connect "kind" "${reg_name}"

  - run:
      name: Create KinD cluster with private container registry
      command: |
        ./kubectl apply -f test/fixtures/job.yaml
        sleep 10
        ./kubectl logs -f job.batch/my-job
