machine:
  enabled: true

working_directory: ~/kubernetes-monitor

steps:
  - checkout

  - run:
      name: Get IP
      command: |
        ifconfig -a | grep -A 1 eth0 | grep "inet addr:" | awk '{print $2}' | cut -d ':' -f2
