version: 2.1

main_branches_filter: &main_branches_filter
  filters:
    branches:
      ignore:
        - staging
        - master

workflows:
  PR_TO_STAGING:
    jobs:
      - test_test:
          <<: *main_branches_filter
